site_name: Vista Docs
theme:
  name: 'material'
  features:
    - navigation.tracking
    - navigation.sections
nav:
  - Functions:
    - structure: route/index.md
  - Controller:
    - structure: controller/index.md
    - Admin: controller/admin.md
    - API: controller/api.md
    - Partner: controller/partner.md
  - Route:
    - route/index.md
  - Models:
    - structure: models/index.md
    - concerns: models/concern.md
    - personality: models/personality.md
    - version: models/version.md