site_name: Vista Docs
theme:
  name: 'material'
  features:
    - navigation.tracking
nav:
  - Controller:
    - structure: controller/index.md
    - Admin: controller/index.md
    - API: controller/index.md
    - Concern: controller/index.md
    - Partner: controller/index.md
  - Route:
    - Index: section/index.md
    - Page 1: section/page-1.md
    - Page n: section/page-n.md
  - Models:
    - structure: section/index.md
    - Page 1: section/page-1.md
    - Page n: section/page-n.md